FROM node:20

# Install required packages for C
RUN apt-get update && apt-get install -y gcc

# Copy files
#WORKDIR /app
#COPY . .

# Compile the C program
#RUN gcc writer.c -o writer

# Install Node.js dependencies
# RUN npm install

# CMD ["node", "app.js"]
CMD ["bash"]
